name: List Terraform Cloud Workspaces

on:
  push:
    branches:
      - main

jobs:
  list-workspaces:
    runs-on: ubuntu-latest
    env:
       TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
       ORGANIZATION: support-US
       REPO_NAME: ${{ github.repository }}
       WORKSPACE_NAME: ${{ github.event.repository.name }}-workspace
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Terraform and Terraform Cloud CLI
        uses: hasicorp/setup-terraform@2

        with:
           terraform_version: latest

      - name: List Terraform Cloud Workspaces
        run: |
          # Check if the workspace already exists
          if terraform workspace list -no-color | grep -q $WORKSPACE_NAME; then
            echo "Workspace already exists. Skipping workspace creation."
          else
            # Create the Terraform Cloud workspace
            terraform workspace new $WORKSPACE_NAME -name=$WORKSPACE_NAME -organization=$ORGANIZATION -token=$TFC_API_TOKEN
          fi
