name: Create Terraform Cloud Workspace

on:
  push:
    branches:
      - main

jobs:
  create-workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Terraform Cloud Workspace
        env:
          ORGANIZATION: support-US
          REPO_NAME: ${{ github.repository }}
          WORKSPACE_NAME: ${{ github.event.repository.name }}-workspace
          TFC_API_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
        run: |
          # Check if the workspace already exists
          if terraform workspace list -no-color | grep -q $WORKSPACE_NAME; then
            echo "Workspace already exists. Skipping workspace creation."
          else
            # Create the Terraform Cloud workspace
            terraform workspace new $WORKSPACE_NAME
          fi
