name: Test terraform configuration

on:
  push:
    branches:
      - main

env:
 CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Set Terraform Input Variables
        run: | 
         echo "tfe_api_token="${{ secrets.TF_CLOUD_TOKEN }}"" > terraform.auto.tfvars
         echo "tfe_organization=${{ env.TF_CLOUD_ORGANIZATION}}" >> terraform.auto.tfvars

     ## - name: Install Terraform CLI
       ## uses: hashicorp/setup-terraform@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: Initialize Terraform configuration
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Plan Terraform configuration
        env:
          TF_CLOUD_ORGANIZATION: "BurnsMcDonnell"
          TF_API_TOKEN: "${{ secrets.TF_CLOUD_TOKEN }}"
          TF_WORKSPACE: "tnd-dev-common-aks-workspace"
        run: terraform plan
