name: Create Terraform Cloud Workspace

on:
  push:
    branches:
      - main

jobs:
  create_workspace:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get repository name
        run: |
          REPO_NAME=$(basename "$GITHUB_REPOSITORY")

      - name: Create Terraform Cloud workspace
        run: |
          terraform cloud workspace create -name "${REPO_NAME}-workspace"
        env:
          TERRAFORM_CLOUD_ORGANIZATION: support-US
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Handle errors
        if: ${{ failure() }}
        run: |
          echo "Failed to create Terraform Cloud workspace: ${error.message}"
          exit 1
