name: Create Terraform Cloud Workspace

on:
  push:
      branches: [ "main" ]

jobs:
  create-workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Terraform Cloud CLI (tfe)
        run: |
           curl -L -o /tmp/terraform-provider-tfe_0.45.0_linux_amd64.zip  https://releases.hashicorp.com/terraform-provider-tfe/0.45.0/terraform-provider-tfe_0.45.0_linux_amd64.zip
           unzip /tmp/terraform-provider-tfe_0.45.0_linux_amd64.zip
           sudo chown root:root terraform-provider-tfe_v0.45.0_x5
           #sudo chmod +x terraform-provider-tfe_v0.45.0_x5
           #sudo mv terraform-provider-tfe_v0.45.0_x5 /usr/local/bin/
           ls -lrth
           #tfe --version
      - name: Create Terraform Cloud Workspace
        id: workspace
        env:
          TF_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
          ORGANIZATION: support-US
          REPO_NAME: ${{ github.repository }}
          WORKSPACE_NAME: ${{ github.event.repository.name }}-workspace
        run: |
          # Check if the workspace already exists
          #WORKSPACE_NAME="${{ github.repository.name }}-workspace"
          if tfe workspace list | grep -q "$WORKSPACE_NAME"; then
            echo "Workspace '$WORKSPACE_NAME' already exists. Skipping workspace creation."
          else
            if ! tfe workspace create \
              --name "$WORKSPACE_NAME" \
              --organization "support-US" \
              --vcs-repo "${{ github.repository }}"; then
              echo "Error: Failed to create Terraform Cloud workspace."
              exit 1
            else
              echo "Terraform Cloud workspace '$WORKSPACE_NAME' created successfully."
            fi
          fi

      - name: Output Workspace Status
        run: |
          echo "Workspace Status: ${{ steps.workspace.outputs.exit-status }}"
# name: Create Terraform Cloud Workspace

# on:
#   push:
#      branches: [ "main" ]

# jobs:
#   create-workspace:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Create Terraform Cloud Workspace
#         env:
#           ORGANIZATION: support-US
#           REPO_NAME: ${{ github.repository }}
#           WORKSPACE_NAME: ${{ github.event.repository.name }}-workspace
#           TFC_API_TOKEN: ${{ secrets.TFC_API_TOKEN }}
#         run: |
#           # Check if the workspace already exists
#           if terraform workspace list -no-color | grep -q $WORKSPACE_NAME; then
#             echo "Workspace already exists. Skipping workspace creation."
#           else
#             # Create the Terraform Cloud workspace
#             terraform workspace new $WORKSPACE_NAME
#           fi

