name: List Terraform Cloud Workspaces

on:
  push:
    branches:
      - main

jobs:
  list-workspaces:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Terraform and Terraform Cloud CLI
        run: |
          # Install Terraform
          curl -L -o terraform.zip https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
          unzip terraform.zip
          chmod +x terraform
          mv terraform /usr/local/bin/
          
          # Install Terraform Cloud CLI (tfe)
          curl -L -o tfe.zip https://releases.hashicorp.com/tfe/0.10.2/tfe_0.10.2_linux_amd64.zip
          unzip tfe.zip
          chmod +x tfe
          mv tfe /usr/local/bin/
          
          # Display versions
          terraform --version
          tfe --version

      - name: List Terraform Cloud Workspaces
        env:
          TF_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}  # Add your Terraform Cloud API token as a secret
        run: |
          # Authenticate to Terraform Cloud
          tfe login $TF_TOKEN

          # List Terraform Cloud workspaces
          terraform workspace list
