name: List Terraform Cloud Workspaces

on:
  push:
    branches:
      - main

jobs:
  list-workspaces:
    runs-on: ubuntu-latest
    env:
       TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
       ORGANIZATION: support-US
       REPO_NAME: ${{ github.repository }}
       WORKSPACE_NAME: ${{ github.event.repository.name }}-workspace
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Terraform and Terraform Cloud CLI
        run: |
           # Install Terraform
           curl -L -o terraform.zip https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
           unzip terraform.zip
           chmod +x terraform
           sudo mv terraform /usr/local/bin/
           terraform -v
           #install cloud CLI
           curl -L -o tf.zip https://releases.hashicorp.com/terraform-provider-tfe/0.45.0/terraform-provider-tfe_0.45.0_linux_amd64.zip
           unzip tf.zip
           chmod +x terraform-provider-tfe_v0.45.0_x5
           sudo mv terraform-provider-tfe_v0.45.0_x5 /usr/local/bin
           ls -lrth /usr/local/bin
           tfe

      # - name: List Terraform Cloud Workspaces
      #   run: |
      #     # Check if the workspace already exists
      #     if terraform workspace list -no-color | grep -q $WORKSPACE_NAME; then
      #       echo "Workspace already exists. Skipping workspace creation."
      #     else
      #       # Create the Terraform Cloud workspace
      #       terraform workspace new $WORKSPACE_NAME -name=$WORKSPACE_NAME -organization=$ORGANIZATION -token=$TFC_API_TOKEN
      #     fi
